### ISSUE TITLE
USB map found; USBinsertALL not found

### ISSUE THREAD

**Issue by marmasin** [corpnewt/USBMap#10]
I he installed Mojave on my XPS 9360 ( i7 7500 with intel HD graphics). 
Used Open core bootloader
Wanted to do [Intel USB Mapping ](https://dortania.github.io/USB-Map-Guide/intel-mapping/intel.html)
and by following this guide started USBmap but when I start it i get message:
Plist: USBMap
USBinjectAll: Not found ; NVRAM arg.....

**Comment by paulhobbel** [comment]
I am currently experiencing the same issue, USBInjectAll is not being loaded

**Comment by corpnewt** [comment]
The master branch's codebase has been updated to no longer require USBInjectAll.  The issues you faced were likely due to Sniki's branch of USBInjectAll being built against a newer SDK, which prevents it from loading on older macOS versions.

-CorpNewt
