### ISSUE TITLE
Edit existing USBMap.kext

### ISSUE THREAD

**Issue by francisceril** [corpnewt/USBMap#12]
Hi, not really an issue but a question.

So I don't have the USB.plist of my existing map and I wanted to turn ON the Bluetooth. Will it work if I just edit the Info.plist of the kext and add the desired port?

Thanks.

**Comment by corpnewt** [comment]
Sorry about the late answer - but yes, you can edit the Info.plist of the USBMap.kext to make changes as needed.  That's how the injector kexts were edited prior to scripts/applications that automate the process.

-CorpNewt
