### ISSUE TITLE
AMD some ports are missing (compared to ioreg)

### ISSUE THREAD

**Issue by hrytskivr** [corpnewt/USBMap#14]
So I have XHC1 renamed to SHCI controller, which has 10 ports PRT1-10.
IOReg app shows all 10 but USBMap show only the first one, what could be the issue?
![Screenshot 2020-10-17 at 18 15 54](https://user-images.githubusercontent.com/23154876/96346515-d9d18500-10a4-11eb-8811-b8028cbc62eb.png)
![Screenshot 2020-10-17 at 18 16 02](https://user-images.githubusercontent.com/23154876/96346517-db02b200-10a4-11eb-9cf6-7d6ba384d982.png)

**Comment by corpnewt** [comment]
Can you run the following in the terminal and send the resulting `ioreg.txt` on the Desktop to me:  `ioreg -lw0 > ~/Desktop/ioreg.txt`

-CorpNewt

**Comment by hrytskivr** [comment]
[ioreg.txt](https://github.com/corpnewt/USBMap/files/5396445/ioreg.txt)

**Comment by hrytskivr** [comment]
@corpnewt ^^

**Comment by corpnewt** [comment]
Sorry about the late reply to this - I took a look through the ioreg and it seems that at least one device has a newline (`\n`) in its name, which broke the prior path-walking code.  This should be fixed now as of [this commit](https://github.com/corpnewt/USBMap/commit/47fc845de822ea351ff58ecde654cd390f8a0a58).

-CorpNewt

**Comment by corpnewt** [comment]
Just for the sake of being complete - here are some screenshots leveraging your `ioreg.txt` as the source:

![image](https://user-images.githubusercontent.com/12772521/103089319-3f655480-45b3-11eb-8fe8-fbbe03ab7b47.png)

![image](https://user-images.githubusercontent.com/12772521/103089327-47bd8f80-45b3-11eb-9f85-191393d109c0.png)

The problem device was the `OBINS AnnePro2`.  In the `ioreg.txt`, it's listed as the following (with `AnnePro2` on the following line):
```
    | |   |   |   | +-o OBINS
AnnePro2@61100000  <class IOUSBHostDevice, id 0x10000062b, registered, matched, active, busy 0 (124 ms), retain 49>
```

-CorpNewt

**Comment by hrytskivr** [comment]
@corpnewt Nice one, thx!
