### ISSUE TITLE
USBMap - USBInjectAll old version update..?

### ISSUE THREAD

**Issue by slagteriet** [corpnewt/USBMap#2]
Hi @corpnewt I'm trying to follow this great guide on my latest build [here](https://www.tonymacx86.com/threads/high-sierra-wont-install-z390-aorus-pro-wifi-rev-1-0-intel-core-i9-9900k-coffee-lake-s-full-guide.274311/post-1935276)

First of all the USBInjectAll files that the script loads is older, and I tried to remove and install version 0.7.1  both within Clover Configurator and from downloading [RehabMan-USBInjectAll-2018-1108.zip](https://bitbucket.org/RehabMan/os-x-usb-inject-all/downloads/)

![USB mapper](https://user-images.githubusercontent.com/23503773/55494978-2af16380-563c-11e9-87a5-01d517102436.png)

How should I make the script load the latest one ?

**Comment by corpnewt** [comment]
The script does not load USBInjectAll for you - it just reports the version currently loaded by the system.  I would bet you have USBInjectAll installed in multiple places, and the older version is taking precedence.

-CorpNewt

**Comment by slagteriet** [comment]
never mind im a n00b.. found it in  **/Library/Extensions** will try put latest version in there.

When I toggled the usb 2.0 out in the first run. I was not able to get into desktop . had to remove boot args to get back again.. but let me try with 0.7.1 of USBInjectAll

![in there](https://user-images.githubusercontent.com/23503773/55495617-9d167800-563d-11e9-8ca0-5aa36d75a2de.png)

**Comment by corpnewt** [comment]
Feel free to comment here if there are more issues - but as this is not an issue with the script, I'm going to go ahead and close this issue.

-CorpNewt

**Comment by slagteriet** [comment]
yes. ofc.. but its now 0.7.1 version.. now I will try get that USB-C working ..
Thanks for quick reply!
![0 7 1](https://user-images.githubusercontent.com/23503773/55496018-6c830e00-563e-11e9-9b04-63f2b3f92091.png)
