### ISSUE TITLE
wrong results

### ISSUE THREAD

**Issue by roddy20** [corpnewt/USBMap#24]
![Снимок экрана 2021-04-22 в 2 25 52](https://user-images.githubusercontent.com/5681302/115634476-5e31e880-a312-11eb-9cbc-0c73de41c83b.png)
XHC1 is not detected here

![Снимок экрана 2021-04-22 в 2 26 21](https://user-images.githubusercontent.com/5681302/115634541-7a358a00-a312-11eb-9fdf-9bfae59be439.png)
but XHCI ports are assigned to USB2

[IORegistry.zip](https://github.com/corpnewt/USBMap/files/6354448/IORegistry.zip)

USB are ICH9 and XHCI is FL1100
[USBMap.kext.zip](https://github.com/corpnewt/USBMap/files/6354455/USBMap.kext.zip)

**Comment by corpnewt** [comment]
Should be fixed in [this commit](https://github.com/corpnewt/USBMap/commit/7cb5a8c6539a7e9d100f0a4bf304a1f4e7077c32).  Thanks for letting me know.

-CorpNewt

**Comment by roddy20** [comment]
Thanks
seems to be much better now

![Снимок экрана 2021-04-26 в 19 14 33](https://user-images.githubusercontent.com/5681302/116117189-a2cbd400-a6c4-11eb-95fe-433345ee957f.png)

![Снимок экрана 2021-04-26 в 19 15 00](https://user-images.githubusercontent.com/5681302/116117151-98a9d580-a6c4-11eb-9be4-a3ea044a7a72.png)

**Comment by roddy20** [comment]
[USBMap.kext.zip](https://github.com/corpnewt/USBMap/files/6378588/USBMap.kext.zip)
[USBMapLegacy.kext.zip](https://github.com/corpnewt/USBMap/files/6378591/USBMapLegacy.kext.zip)
but two ports are still SS* not PRT*
![Снимок экрана 2021-04-26 в 19 22 20](https://user-images.githubusercontent.com/5681302/116117470-f50cf500-a6c4-11eb-980f-6c1f02507340.png)

**Comment by corpnewt** [comment]
The names are completely arbitrary.  The OS does not interpret them at all.  I've used the traditional `HSxx` and `SSxx` naming scheme to represent USB 2 and USB 3 personalities respectively on an XHCI controller and `PRTx` for EHCI, UHCI, and OHCI controllers as seen [here](https://github.com/corpnewt/USBMap/blob/master/USBMap.py#L562-L569).  You could rename those entries to `BOBx` and they would show up in IOReg - the OS doesn't care what they are.

I took your IOReg.txt and ran USBMap.command with it - enabled all ports and generated the USBMap.kext - and the ports are all named correctly (including the same controller listed in your screenshot):

![image](https://user-images.githubusercontent.com/12772521/116119063-9d9a6500-a683-11eb-83cc-afaadf301fc0.png)

[USBMap.kext.zip](https://github.com/corpnewt/USBMap/files/6378663/USBMap.kext.zip)

As for the `kUSBxxx` values - those are expected to be setup in SSDT-USBX.aml (or SSDT-EC-USBX.aml) - so the values are not needed in the USBMap.kext.

-CorpNewt

**Comment by roddy20** [comment]
[USB-2021-04-26 19.45.plist.zip](https://github.com/corpnewt/USBMap/files/6378756/USB-2021-04-26.19.45.plist.zip)
I understand..but it is strange
USBE is not XHC*

![Снимок экрана 2021-04-26 в 19 54 01](https://user-images.githubusercontent.com/5681302/116121398-3bfce980-a6c9-11eb-9751-bf5f6ec24b24.png)

**Comment by corpnewt** [comment]
I'm betting it was some garbage data in the USB.plist from prior mapping when the XHCI controller was improperly skipped.  You could try clearing that via `R. Reset All Detected Ports` at the main menu and map again.

-CorpNewt

**Comment by roddy20** [comment]
Yes! Thanks again, it helps!
now all the names are OK
![Снимок экрана 2021-04-26 в 20 16 20](https://user-images.githubusercontent.com/5681302/116123965-55ebfb80-a6cc-11eb-8005-d1e61aa7bf7c.png)
