### ISSUE TITLE
Error running USBmap

### ISSUE THREAD

**Issue by EmmJSee** [corpnewt/USBMap#29]
Hi there 

I get this error:

USBMap.command 
  File "USBMap.command", line 9
    NL=$'\n'

running on Debian Buster, with latest available Python 3.7

Cheers

**Comment by corpnewt** [comment]
Hey there - USBMap only runs in macOS. The USBMapInjectorEdit script is cross platform - but only serves to edit an existing injector kext.

-CorpNewt
