### ISSUE TITLE
USBmap problem with USB 3.0 ports (ASM1042 USB 3.0 controller)

### ISSUE THREAD

**Issue by rudi48** [corpnewt/USBMap#3]
Hello CorpNewt,

I had a problem to figure out the USB ports on an ASUS-H81M_PLUS mainboard.

To my understanding the rear panel USB 3.0 ports are
 provided from an **ASMedia ASM1042** USB 3.0 controller.

The Intel chipset has USB 2.0 and USB 3.0 (internal):
USB: EH01, 8 Series/C220 Series Chipset Family EHCI #1, 0x8086 0x8C26
USB: XHC,  8 Series/C220 Series Chipset Family xHCI #1, 0x8086 0x8C31

When I look at **Hackintool_H81M_USB_USBmap.png** I do not see any **SSxx ports**.
To my surprise the ASM1042 ports work with USB 3.0,
but the names are different: SSP1, SSP2.
See also **ASUS-H81M-PLUS-Rear-Panel_USB.png**.

You program USBmap.command shows **USB.plist_H81M.txt**

The Clover ACPI Patches for USB are:
change EHC1 to EH01
change EHC2 to EH02
change XHCI to XHC_
change XHC1 to XHC_

I have also appended **EssentialsList-2019-05-19 15.52.14_ASUS-H81M-PLUS.zip**

Now it works, but it was a long run.

I know, it is a special mainboard, but may be it helps you in one case.

By the way, it is useful to route the desktop screen to a VNC client.
That avoids the problem, that a missing USB keyboard and mouse need some
effort to fix.

Regards, Rudolf  DL5FA

```
File: USB.plist.txt. 2019-05-19  RR
[#] 1. HS01 - Type 3 - Controller XHC
[#] 2. HS02 - Type 3 - Controller XHC
[#] 3. HS03 - Type 0 - Controller XHC
    - composite_device
[#] 4. HS04 - Type 0 - Controller XHC
    -  USB OPTICAL MOUSE
[#] 5. HS05 - Type 3 - Controller XHC
    - ADATA USB Flash Drive
[#] 6. HS06 - Type 3 - Controller XHC
[#] 7. HS07 - Type 0 - Controller XHC
    - Bluetooth USB Host Controller
[ ] 8. HS08 - Type 3 - Controller XHC
[#] 9. HS09 - Type 0 - Controller XHC
[#] 10. HS10 - Type 0 - Controller XHC
[#] 11. SSP1 - Type 3 - Controller XHC
[#] 12. SSP2 - Type 3 - Controller XHC
[#] 13. PR11 - Type 0 - Controller EH01
    - hub_device
[ ] 14. PR12 - Type 0 - Controller EH01
[ ] 15. PR13 - Type 0 - Controller EH01
[ ] 16. PR14 - Type 0 - Controller EH01
[ ] 17. PR15 - Type 0 - Controller EH01
[ ] 18. PR16 - Type 0 - Controller EH01
[ ] 19. PR17 - Type 0 - Controller EH01
[ ] 20. PR18 - Type 0 - Controller EH01
[ ] 21. HP11 - Type 0 - Controller HUB1
[ ] 22. HP12 - Type 0 - Controller HUB1
[ ] 23. HP13 - Type 0 - Controller HUB1
[ ] 24. HP14 - Type 0 - Controller HUB1
[ ] 25. HP15 - Type 0 - Controller HUB1
[ ] 26. HP16 - Type 0 - Controller HUB1
[ ] 27. HP17 - Type 0 - Controller HUB1
[ ] 28. HP18 - Type 0 - Controller HUB1

Selected:  XHC:11, EH01:1, HUB1:0
```

![ASUS-H81M-PLUS-Rear-Panel_USB](https://user-images.githubusercontent.com/6186606/57985305-29ea8900-7a66-11e9-8b7e-6d42a3f13e2b.png)

[EssentialsList-2019-05-19 15.52.14_ASUS-H81M-PLUS.zip](https://github.com/corpnewt/USBMap/files/3195346/EssentialsList-2019-05-19.15.52.14_ASUS-H81M-PLUS.zip)

![Hackintool_H81M_USB_USBmap](https://user-images.githubusercontent.com/6186606/57985346-a67d6780-7a66-11e9-9067-defaa86645cc.png)

[USB.plist_H81M.txt](https://github.com/corpnewt/USBMap/files/3195347/USB.plist_H81M.txt)

**Comment by corpnewt** [comment]
The USBMap script only customizes USB ports for USBInjectAll.kext - which only works with Intle chipset controlled ports.  The ASMedia ports are likely located on a generic (PXSX) device.  Either way, the SSDT generated will not affect them as USBInjectAll itself ignores them.

Some third party USB controllers work OOB, others may require GenericUSBXHCI.kext, and others still may not work at all.  Unfortunately, this is not within the scope of USBMap as it only serves to map the chipset-controlled ports.

-CorpNewt

**Comment by viniciusmi00** [comment]
> The USBMap script only customizes USB ports for USBInjectAll.kext - which only works with Intel chipset controlled ports. The ASMedia ports are likely located on a generic (PXSX) device. Either way, the SSDT generated will not affect them as USBInjectAll itself ignores them.
> 
> Some third party USB controllers work OOB, others may require GenericUSBXHCI.kext, and others still may not work at all. Unfortunately, this is not within the scope of USBMap as it only serves to map the chipset-controlled ports.
> 
> -CorpNewt

I'm trying to get my USB 3.0 ports to work (ASMedia 1042). GenericUSBXHCI.kext (v1.2.11) is not working in Big Sur. 
Do you know how I can make ASMedia 1042 work in Big Sur?
