### ISSUE TITLE
Question about using the tool, readme doesn't specify

### ISSUE THREAD

**Issue by PencilNotPen** [corpnewt/USBMap#30]
Does this tool require USBInjectAll.kext to use it? Does it require XHCIPortLimit enabled in config.plist to use it? Or should the system be completely vanilla before running the tool?

Thanks

**Comment by PencilNotPen** [comment]
> Does this tool require USBInjectAll.kext to use it? Does it require XHCIPortLimit enabled in config.plist to use it? Or should the system be completely vanilla before running the tool?
> 
> Thanks

I think I've managed to work it out more or less, although the port limit patch and kext produce some strange effects on my system. All ports are now identified.

A quick follow up: once all ports have been identified and marked, do I set HSxx to Port Type 0 for USB 2, or Type 3 for USB 3? I have matching sets for e.g. SS03/HS03, SS04/HS04 etc. I understand I need to include both SS03 and HS03 in my map to work with both USB 2 and USB 3 devices, but should I make both SS03 and HS03 as Connector Type 3, or mark SS03 as Type 3 and HS03 as Type 0?

I hope that makes sense, thanks for your help!

**Comment by corpnewt** [comment]
Hey there - under the Features heading of the ReadMe you can see the following:

![image](https://user-images.githubusercontent.com/12772521/126055033-bd55799a-b70d-42dc-a214-a8c6eb699dc3.png)

Whether or not you use `XhciPortLimit` is more dependent on what OS you're running as that quirk is unreliable on macOS 11.3 and newer.

Regarding the types to set - those should reflect the type of the *physical* port; so the HSxx personality of a type-A USB 3 port would still have its type set to 3.

Hopefully that answers your questions,

-CorpNewt
