### ISSUE TITLE
USBMapInjectorEdit.command Is it temporary to disable unuseful ports during mapping?

### ISSUE THREAD

**Issue by oldman20** [corpnewt/USBMap#41]
![Screen Shot 2022-07-25 at 09 47 54](https://user-images.githubusercontent.com/39668756/180684155-b3074110-5e6e-41e0-945e-fbd0118e7d24.png)
what's about USBMapInjectorEdit.command? Is it temporary to disable unuseful ports?
I can use USBMap/ USBMapLegacy/ USBMap Dummy depending which boot method, right?

![Screen Shot 2022-07-25 at 09 48 42](https://user-images.githubusercontent.com/39668756/180685096-b4f57e60-e32d-46a2-905f-5251d946eb89.png)
And I don't understand much about S, C, L Option. Anyone can explain for me? Thank!
I did like screenshot is properly?
![Screen Shot 2022-07-25 at 09 55 45](https://user-images.githubusercontent.com/39668756/180687016-c96bc37f-f2bd-4953-a6a4-f3bf5c5ec6ce.png)
![Screen Shot 2022-07-25 at 09 55 53](https://user-images.githubusercontent.com/39668756/180687040-6c01348e-f484-4256-ba2f-d4f426005b68.png)
![Screen Shot 2022-07-25 at 09 56 50](https://user-images.githubusercontent.com/39668756/180687404-22fce465-bd9b-44b7-abbd-8f600e9864c9.png)
![Screen Shot 2022-07-25 at 09 59 53](https://user-images.githubusercontent.com/39668756/180688524-a36b6e46-9428-4b29-acc5-20d9b68df47c.png)

**Comment by corpnewt** [comment]
Hey there - as I mentioned in [the other issue](https://github.com/corpnewt/USBMap/issues/40#issuecomment-1193497460):
> Correct - it just gives you a quick, cross platform way to edit the injector.  It makes it easy to toggle ports on or off within an existing injector (like the dummy USBMap.kext).
>
> I also added the ability for it to change types, add nicknames, etc - it's akin to a self-contained copy of the `P. Edit & Create USBMap.kext` option within USBMap's main menu which works by editing, and not creating a new injector kext.

But - as you've asked here, onto the current questions at hand:

> I can use USBMap/ USBMapLegacy/ USBMap Dummy depending which boot method, right?

USBMap and USBMapLegacy just leverage different IOClasses.  AFAIK USBMap will work, even on older OSes - but some may have better luck on pre-Catalina OSes with USBMapLegacy.

> And I don't understand much about S, C, L Option. Anyone can explain for me? Thank!

The IOKitPersonalities within USBMap and USBMapLegacy are bound to a certain SMBIOS - if you change your SMBIOS and intend to reuse the same map - you need to change the SMBIOS targeted within the injector to match the target machine via the `S` option.

`C` changes all IOKitPersonalities to use the new `AppleUSBHostMergeProperties` IOClass- which is what USBMap.kext uses by default.

`L` changes all IOKitPersonalities to use the older `AppleUSBMergeNub` IOClass - which is what USBMapLegacy.kext uses by default.

You can still respond in the prior issue you had posted - I've just closed it is all.

Hopefully that answers your questions though?

-CorpNewt

**Comment by oldman20** [comment]
Thanks, enough for me
Keep great work! Good day to you!
