### ISSUE TITLE
Renaming XHCI/XHC1 -> XHC_

### ISSUE THREAD

**Issue by codecowboy** [corpnewt/USBMap#5]
In order to meet the prerequisite XHCI/XHC1 -> XHC_ , What would the hex values be when adding this in Clover Configurator? I originally renamed these as per the vanilla guide.

**Comment by corpnewt** [comment]
```
XHCI -> 58484349
XHC1 -> 58484331
XHC_ -> 5848435F
```
Not an issue with the script though - so closing the issue.

-CorpNewt
