### ISSUE TITLE
Unable to load UsbMapDummy.kext or UsbMap.kext anymore

### ISSUE THREAD

**Issue by andrejhrasko** [corpnewt/USBMap#54]
Hello. Something happened and I am not able to load UsbMapDummy.kext or UsbMap.kext anymore. Not sure what happened.

kexstat does not show it as loaded and ports in USBMap does not show UKxx naming scheme.
I do not have any other USB related kext or ssdt enabled and I do not have XhciPortLimit enabled.

I just have a feeling that I clicked on Inject button in Hackintool 4.0.3 under the USB tab. I think that since then it stopped working.

Do you please have any ideas? Thanks.

**Comment by corpnewt** [comment]
Hmmm - USBMap.kext and USBMapDummy.kext are just codeless injectors - so you cannot verify they're loaded using `kextstat` - as there's no binary within them.  If you're not getting the `UKxx` naming, that implies something else is likely overriding your USB setup (or that the injector is not being injected properly).

It might be worth checking the output of `kextstat | grep -iv com.apple` to see what kexts you currently have loaded - and checking your debug `opencore-[timestamp].txt` logs to see what OC is injecting.  If you're not able to find any hints there - let me know and I'll see if there's anywhere else you could look.

I will close this issue for the time being - as it's not an issue with USBMap itself, but I'll still reply here in the hopes that we can correct this.

-CorpNewt
