### ISSUE TITLE
How to reset all usb ports back the beginning?

### ISSUE THREAD

**Issue by okbrown** [corpnewt/USBMap#56]
For some reason I am unable to to view all the ports that originally displayed before I selected the ones I thought I needed.
This process started because I was unable to get the Bluetooth working, and according the Dortania docs, I need to map the right USB ports. Well I have tried removing the USBPorts.kext, resetting the NVMRam, even reinstalling everything from scratch, yet still the ports will not come back.

What is required to resolve this?

**Comment by corpnewt** [comment]
USBMap won't create a USBPorts.kext, it creates a USBMap.kext or USBMapLegacy.kext (or versions that also include "Dummy" in the name).  You are likely thinking of [Hackintool](https://github.com/benbaker76/Hackintool).  Regardless, USBMap or Hackintool's injector kexts should only affect macOS when you've booted with them present, and enabled in your EFI and config.plist.  Removing or disabling the kext and rebooting undoes anything the kext would have done.

I cannot vouch for whether or not you've used something else prior - or how the initial state of your machine's USB was set up, however, so I'm not sure how the ports looked before mapping.  You also should not ever need to reset NVRAM for USB mapping.  Mapping using current approaches should only be done via kexts or ACPI - neither of which affect NVRAM.

Were I in your shoes, I'd try mapping all ports again following the relevant guide for whatever tool you're using.  If you're using Hackintool, consult thier documentation.  For USBMap, consult the quick start guide in the readme.  If mapping manually, you can consult the Dortania guide.

-CorpNewt

**Comment by okbrown** [comment]
Hey, Thanks for your reply, its been a while I cant remember how I got them all back, but found a very good guide that explained how to do it properly. Its all working now. Thanks.
