### ISSUE TITLE
Wrong UIA boot arg in Readme.md

### ISSUE THREAD

**Issue by edoardo-conti** [corpnewt/USBMap#8]
In Readme.md at some point you'll find:
`-uia_exclude-hs uia_include=HSxx,HSxx`

_-uia_exclude-hs_ it's wrong, the correct one: **-uia_exclude_hs**

source: [https://github.com/RehabMan/OS-X-USB-Inject-All](url)

**Comment by corpnewt** [comment]
The master branch's codebase has been updated to no longer require USBInjectAll.

-CorpNewt
